# NumPy Assignment
Course: Python Programming
Topic: NumPy – Basics to Advanced

Run each code cell using the ▶ button in Google Colab.

## Question 1 – Student Marks Array

In [1]:
import numpy as np

marks = np.array([78, 65, 89, 56, 92])

print("Marks:", marks)
print("Dimensions:", marks.ndim)
print("Shape:", tuple(marks.shape))
print("Number of elements:", marks.size)
print("Type of data:", marks.dtype)


Marks: [78 65 89 56 92]
Dimensions: 1
Shape: (5,)
Number of elements: 5
Type of data: int32


## Question 2 – Student Marks Access

In [2]:
import numpy as np

scores = np.array([72, 85, 64, 90, 76])

print("Marks:", scores)
print("First student:", scores.take(0))
print("Third student:", scores.take(2))
print("Last student:", scores[-1])
print("First three:", scores[:3])
print("Second through fourth:", scores[1:4])
print("Last two:", scores[-2:])


Marks: [72 85 64 90 76]
First student: 72
Third student: 64
Last student: 76
First three: [72 85 64]
Second through fourth: [85 64 90]
Last two: [90 76]


## Question 3 – Subject-wise Marks

In [3]:
import numpy as np

marks = np.array([
    78, 85, 90,
    65, 72, 80,
    88, 91, 84,
    56, 62, 70,
    95, 89, 92
])

matrix = marks.reshape(-1, 3)

print("One-dimensional array:")
print(marks)
print("Student-subject matrix:")
print(matrix)


One-dimensional array:
[78 85 90 65 72 80 88 91 84 56 62 70 95 89 92]
Student-subject matrix:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


## Question 4 – Internal and External Marks

In [4]:
import numpy as np

internal = np.array([20, 18, 22, 19, 21])
external = np.array([65, 70, 68, 72, 75])

total = np.add(internal, external)

print("Internal:", internal)
print("External:", external)
print("Combined marks:", total)


Internal: [20 18 22 19 21]
External: [65 70 68 72 75]
Combined marks: [85 88 90 91 96]


## Question 5 – Pass Percentage Analysis

In [5]:
import numpy as np

marks = np.array([45, 78, 56, 32, 91])

qualified = marks[marks >= 50]

print("Marks:", marks)
print("Pass condition:", marks >= 50)
print("Students who passed:", qualified)
print("Number passed:", qualified.size)


Marks: [45 78 56 32 91]
Pass condition: [False  True  True False  True]
Students who passed: [78 56 91]
Number passed: 3


## Question 6 – Average Marks

In [6]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

student_averages = marks.sum(axis=1) / marks.shape[1]

print("Marks:")
print(marks)
print("Average of each student:")
print(student_averages)


Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Average of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


## Question 7 – Class Performance Statistics

In [7]:
import numpy as np

scores = np.array([67, 82, 91, 74, 58])

summary = {
    "Total": scores.sum(),
    "Average": scores.mean(),
    "Highest": scores.max(),
    "Lowest": scores.min(),
    "Standard Deviation": scores.std()
}

print("Marks:", scores)
for label, value in summary.items():
    print(label + ":", value)


Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard Deviation: 11.46472851837321


## Question 8 – Subject-wise Performance

In [8]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

subject_total = marks.T.sum(axis=1)

print("Marks:")
print(marks)
print("Total for each subject:", subject_total)


Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total for each subject: [382 399 416]


## Question 9 – Student-wise Performance

In [9]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

student_total = marks.sum(axis=1)

print("Marks:")
print(marks)
print("Total for each student:", student_total)


Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total for each student: [253 217 263 188 276]


## Question 10 – Student Ranking

In [10]:
import numpy as np

marks = np.array([245, 278, 219, 290, 256])

order = np.argsort(-marks)

print("Original marks:", marks)
print("Descending marks:", marks[order])
print("Ranking:")

for position, student_index in enumerate(order, 1):
    print(f"Rank {position} - Student {student_index + 1} - Marks: {marks[student_index]}")


Original marks: [245 278 219 290 256]
Descending marks: [290 278 256 245 219]
Ranking:
Rank 1 - Student 4 - Marks: 290
Rank 2 - Student 2 - Marks: 278
Rank 3 - Student 5 - Marks: 256
Rank 4 - Student 1 - Marks: 245
Rank 5 - Student 3 - Marks: 219


## Question 11 – Duplicate Marks Analysis

In [11]:
import numpy as np

marks = np.array([85, 92, 85, 76, 92])

unique_marks, counts = np.unique(marks, return_counts=True)

print("Original marks:", marks)
print("Marks appearing more than once:", unique_marks[counts > 1])
print("All unique marks:", unique_marks)


Original marks: [85 92 85 76 92]
Marks appearing more than once: [85 92]
All unique marks: [76 85 92]


## Question 12 – Missing Marks

In [12]:
import numpy as np

marks = np.array([78, 85, np.nan, 92, 67])

valid_marks = marks[~np.isnan(marks)]
average = valid_marks.mean()

print("Marks:", marks)
print("Available marks:", valid_marks)
print("Average of available marks:", average)


Marks: [78. 85. nan 92. 67.]
Available marks: [78. 85. 92. 67.]
Average of available marks: 80.5


## Question 13 – Grade Classification

In [13]:
import numpy as np

marks = np.array([95, 82, 74, 61, 45])

grades = np.full(marks.shape, "F", dtype="<U1")
grades[marks >= 60] = "D"
grades[marks >= 70] = "C"
grades[marks >= 80] = "B"
grades[marks >= 90] = "A"

print("Marks:", marks)
print("Grades:", grades)


Marks: [95 82 74 61 45]
Grades: ['A' 'B' 'C' 'D' 'F']


## Question 14 – Random Marks Generation

In [14]:
import numpy as np

rng = np.random.default_rng(10)
marks = rng.integers(0, 101, size=5)

print("Generated marks:", marks)
print("Total:", marks.sum())
print("Average:", marks.mean())
print("Highest:", marks.max())
print("Lowest:", marks.min())
print("Standard deviation:", marks.std())


Generated marks: [78 96 26 20 80]
Total: 300
Average: 60.0
Highest: 96
Lowest: 20
Standard deviation: 30.906310035330975


## Question 15 – Student Performance Analysis

In [15]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

totals = marks.sum(axis=1)
averages = marks.mean(axis=1)
highest_scores = marks.max(axis=1)
lowest_scores = marks.min(axis=1)
class_average = marks.mean()

print("Student Marks:")
print(marks)
print("Total:", totals)
print("Average:", averages)
print("Highest:", highest_scores)
print("Lowest:", lowest_scores)
print("Class Average:", class_average)

above = np.flatnonzero(averages > class_average)
print("Students above class average:")

for student in above:
    print(f"Student {student + 1} - Average: {averages[student]}")


Student Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total: [253 217 263 188 276]
Average: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]
Highest: [90 80 91 70 95]
Lowest: [78 65 84 56 89]
Class Average: 79.8
Students above class average:
Student 1 - Average: 84.33333333333333
Student 3 - Average: 87.66666666666667
Student 5 - Average: 92.0
